<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CuraDesk.Model\CuraDesk.Model.csproj" />
    <ProjectReference Include="..\CuraDesk.Utility\CuraDesk.Utility.csproj" />
  </ItemGroup>

</Project>
